# Default values for big-brother-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

generator:
  image: labbsr0x/metrics-generator-tabajara
  tag: latest
  service: example
  replicaCount: 2
  port: 32865

promster:
  image: labbsr0x/bb-promster
  tag: latest
  port: 9090
  level: 1
  remoteUrl: "" 

etcd:
  image: quay.io/coreos/etcd
  tag: latest 
  port: 2379
  deploy: true

bot:
  image: labbsr0x/bb-bot
  tag: latest
  port: 3000
  deploy: false
