# Default values for big-brother-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

generator:
  service: example
  replicaCount: 2
  port: 32865
  promsterPort: 9091

etcd: true