{{- if .Values.bot.deploy -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bb-bot-svc-{{ .Values.generator.service }}
spec:
  ports:
    - port: {{ .Values.bot.port | default "3000" }}
  selector:
    name: {{ .Release.Name }}-bb-bot-{{ .Values.generator.service }}
{{- end -}}