apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bb-promster-{{ .Values.generator.service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Release.Name }}-bb-promster-{{ .Values.generator.service }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-bb-promster-{{ .Values.generator.service }}
    spec:
      containers:
      - name: {{ .Release.Name }}-bb-promster-{{ .Values.generator.service }}
        image: {{ .Values.promster.image }}:{{ .Values.promster.tag }}
        {{- include "bigbrotherhelm.resource" .Values.promster | indent 8 }}
        env:
          - name: REGISTRY_ETCD_URL
            value: http://etcd.{{ .Release.Namespace }}.svc.cluster.local:2379
          - name: REGISTRY_SERVICE
            value: {{ .Values.generator.service }}
          - name: REGISTRY_ETCD_BASE
            value: /services 
          - name: REGISTRY_SERVICE
            value: {{ .Values.generator.service }}
          - name: REGISTRY_ETCD_BASE
            value: /services
          - name: BB_PROMSTER_LEVEL
            value: "1"
          - name: ETCD_URLS
            value: http://etcd.{{ .Release.Namespace }}.svc.cluster.local:2379
          - name: SCRAPE_ETCD_PATH
            value: /services/{{ .Values.generator.service }} # based on how the examples are configured ($REGISTRY_ETCD_BASE/$REGISTRY_SERVICE)
          {{- if .Values.promster.remoteUrl -}}
          - name: REMOTE_WRITE_URL
            value: {{ .Values.promster.remoteUrl }} #http://nginx.default.svc.cluster.local/api/prom/push
          {{ end }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.promster.port }}
      
    