{{- if .Values.etcd -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: etcd
  template:
    metadata:
      labels:
        name: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.25
        env:
          - name: ETCD_LISTEN_CLIENT_URLS
            value: http://0.0.0.0:2379
          - name: ETCD_ADVERTISE_CLIENT_URLS
            value: http://etcd:2379
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2379
{{- end -}}